
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.spring.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2019-02-14T17:59:18.486+09:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "FileUploadImplService",
                      portName = "FileUploadImplPort",
                      targetNamespace = "http://webservice.spring.com/",
                      wsdlLocation = "http://localhost:9999/webservice/FileUpload?wsdl",
                      endpointInterface = "com.spring.webservice.FileUpload")
                      
public class FileUploadImpl implements FileUpload {

    private static final Logger LOG = Logger.getLogger(FileUploadImpl.class.getName());

    /* (non-Javadoc)
     * @see com.spring.webservice.FileUpload#uploadFile(com.spring.webservice.FileUploader  dfile )*
     */
    public void uploadFile(com.spring.webservice.FileUploader dfile) { 
        LOG.info("Executing operation uploadFile");
        System.out.println(dfile);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
