package com.spring.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2019-02-14T17:59:18.505+09:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://webservice.spring.com/", name = "FileUpload")
@XmlSeeAlso({ObjectFactory.class})
public interface FileUpload {

    @WebMethod
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://webservice.spring.com/", className = "com.spring.webservice.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://webservice.spring.com/", className = "com.spring.webservice.UploadFileResponse")
    public void uploadFile(
        @WebParam(name = "Dfile", targetNamespace = "")
        com.spring.webservice.FileUploader dfile
    );
}
